collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.841484
color:
  saturation: 1
  brandStrength: 0.9994009
  lightness: 1
  brandColors:
    - '#BEC592'
    - '#171615'
    - '#FDFFFF'
    - '#C5884B'
    - '#CFD0CF'
  rhythmicContrast: 0.9032258
layout_spectrum: 0.9229391
name: Testing Out the Goods
