layout_spectrum: 0.108769
typography_spectrum: 0.841484
color:
  saturation: 0.6863406
  lightness: 0.6720067
  brandStrength: 0.9994009
  brandColors:
    - '#270D1F'
    - '#C6B588'
    - '#A3926E'
    - '#F2FCDD'
  rhythmicContrast: 0.3499157
name: Testing Out the Goods
